In [1]:
import torch

In [2]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3=torch.tensor([[5.,6],[7,8]])
t3

tensor([[5., 6.],
        [7., 8.]])

In [6]:
t1.shape

torch.Size([])

In [7]:
t1.shape

torch.Size([])

In [8]:
t2.shape

torch.Size([4])

In [9]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [10]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [11]:
y.backward()

In [12]:
print('dy/dx=',x.grad)
print('dy/dw=',w.grad)
print('dy/db=',b.grad)

dy/dx= None
dy/dw= tensor(3.)
dy/db= tensor(1.)


In [13]:
import numpy as np

In [14]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [15]:
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [16]:
x.dtype

dtype('int32')

In [17]:
y.dtype

torch.int32